// This file is generated by SQLBoiler (https://github.com/volatiletech/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

var TableNames = struct {
	Chart          string
	Exchange       string
	GorpMigrations string
	Market         string
	Tick           string
}{
	Chart:          "chart",
	Exchange:       "exchange",
	GorpMigrations: "gorp_migrations",
	Market:         "market",
	Tick:           "tick",
}
